version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./env/.env.${ENVIRONMENT}  # Load the right env file dynamically
    depends_on:
      - pgdb
    DB_HOST: ${DB_HOST:-db}

  pgdb:
    image: postgres:17
    restart: always
    env_file:
      - ./env/.env.${ENVIRONMENT}  # Load the right database credentials
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$DATABASE_USER", "-d", "$DATABASE_NAME"]
      interval: 5s
      retries: 5
      start_period: 10s
  db:
  image: postgres:15
  restart: always
  environment:
    POSTGRES_DB: "$DATABASE_NAME"
    POSTGRES_USER: "$DATABASE_USER"
    POSTGRES_PASSWORD: "$DATABASE_PASSWORD"
    ConnectionStrings__InfoTrack: "Host=${DB_HOST};Port=5432;Database=${DATABASE_NAME};Username=${DATABASE_USER};Password=${DATABASE_PASSWORD}"

  ports:
    - "5432:5432"
  volumes:
    - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
